#version: '4.3'
services:
  # here we have a single container
  calculix:
    container_name: calculix_bash
    build:     
      context: .devcontainer
      dockerfile: Dockerfile
    tty: true
    stdin_open: true    
    volumes:
      - ./calculix_src:/calculix_src
      - ./calculix_run:/calculix_run